" When no beep or flash is wanted
" Note: This is also needed in gvimrc, or Gvim will "beep"
set vb t_vb=

" Don't show the toolbar
:set guioptions-=T

" Don't show the menu
:set guioptions-=m

" $HOME is necessary for some reason -- filereadable
" doesn't interpolate the ~/
if filereadable(g:vim_dir . "/personal/gvimrc.local")
    exe "so " . g:vim_dir . "/personal/gvimrc.local"
endif

set novisualbell
